superteams_rumbl/web/router.ex
defmodule SuperteamsRumbl.Router do
  use SuperteamsRumbl.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SuperteamsRumbl do
    pipe_through :browser
    get "/users",     UserController, :index
    get "/users/:id", UserController, :show
    get "/", PageController, :index
  end
end

superteams_rumbl/lib/superteams_rumbl/endpoint.ex
defmodule SuperteamsRumbl.Endpoint do
  use Phoenix.Endpoint, otp_app: :superteams_rumbl

  socket "/socket", SuperteamsRumbl.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :superteams_rumbl, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_superteams_rumbl_key",
    signing_salt: "6M5b3g3G"

  plug SuperteamsRumbl.Router
end

superteams_rumbl/lib/superteams_rumbl/repo.ex
defmodule SuperteamsRumbl.Repo do
  use Ecto.Repo, otp_app: :rumbl
end

superteams_rumbl/web/models/user.ex
defmodule SuperteamsRumbl.User do
  use SuperteamsRumbl.Web, :model

  schema "users" do
    field :name, :string
    field :username, :string
    field :password, :string, virtual: true
    field :password_hash, :string

    timestamps
  end
end

superteams_rumbl/web/controllers/page_controller.ex
defmodule SuperteamsRumbl.PageController do
  use SuperteamsRumbl.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

superteams_rumbl/web/controllers/user_controller.ex
defmodule SuperteamsRumbl.UserController do
  use SuperteamsRumbl.Web, :controller

  def index(conn, _params) do
    users = Repo.all(SuperteamsRumbl.User)
    render conn, "index.html", users: users
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get(SuperteamsRumbl.User, id)
    render conn, "show.html", user: user
  end
end

superteams_rumbl/web/views/error_view.ex
defmodule SuperteamsRumbl.ErrorView do
  use SuperteamsRumbl.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

superteams_rumbl/web/views/layout_view.ex
defmodule SuperteamsRumbl.LayoutView do
  use SuperteamsRumbl.Web, :view
end

superteams_rumbl/web/views/page_view.ex
defmodule SuperteamsRumbl.PageView do
  use SuperteamsRumbl.Web, :view
end

superteams_rumbl/web/views/user_view.ex
defmodule SuperteamsRumbl.UserView do
  use SuperteamsRumbl.Web, :view
  alias SuperteamsRumbl.User

  def first_name(%User{name: name}) do
    name
    |> String.split(" ")
    |> Enum.at(0)
  end
end

superteams_rumbl/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello SuperteamsRumbl!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

superteams_rumbl/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Welcome to creating your own Super teams!</h2>
  <p class="lead">A productive web framework involving fictional comic characters.<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

superteams_rumbl/web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table class="table">
  <%= for user <- @users do %>
<tr>
  <td><%= render "user.html", user: user %></td>
  <td><%= link "View", to: user_path(@conn, :show, user.id) %></td>
</tr>
  <% end %>
</table>

superteams_rumbl/web/templates/user/show.html.eex
<h1>Showing User</h1>
<%= render "user.html", user: @user %>

superteams_rumbl/web/templates/user/user.html.eex
<b><%= first_name(@user) %></b> (<%= @user.id %>)